apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app
  namespace: development
  labels:
    name: pingpong-app
    language: node.js
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pingpong-app
      language: node.js
  template:
    metadata:
      name: pingpong-app
      namespace: development
      labels:
        name: pingpong-app
        language: node.js
    spec:
      containers:
        - name: pingpong-app
          image: devlabtwinggo/pingpong-nodejs-app:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-svc
  namespace: development
spec:
  selector:
    name: pingpong-app
    language: node.js
  ports:
    - port: 3000
      targetPort: 3000
